name: myconfig
spec:
  listeners:
  - name: listener_http
    address: 0.0.0.0
    port: 9090
    routes:
    - name: local_route
      prefix: /
      clusters:
      - webcluster
  clusters:
  - name: webcluster
    endpoints:
    - address: 172.70.2.21
      port: 8080
    - address: 172.70.2.22
      port: 8080
