version: '3.3'

services:

  xdsserver:
    image: ikubernetes/envoy-xds-server:v0.1
    container_name: pp-xds-server
    environment:
      - SERVER_PORT=18000
      - NODE_ID=envoy_front_proxy
      - RESOURCES_FILE=/etc/envoy-xds-server/config/config.yaml
    volumes:
    - ./resources:/etc/envoy-xds-server/config/
    networks:
      envoymeshnetwork:
        ipv4_address: 172.70.3.31
        aliases:
        - xdsserver
        - xds-service

networks:
    envoymeshnetwork:
        external:
            name: envoymeshnetwork

