FROM envoyproxy/envoy:v1.23.1

COPY ./fp-envoy.yaml /etc/envoy/envoy.yaml
RUN chmod go+r /etc/envoy/envoy.yaml
CMD apt-get update && apt-get install -y iputils-ping & apt-get install -y curl & apt-get install -y vim
CMD ["/usr/local/bin/envoy", "-c /etc/envoy/envoy.yaml"]
