version: "3.3"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    container_name: pp-front-proxy
    depends_on:
    - service1
    - service2
    ports:
    - 10000:10000
    - 19000:19000

  service1:
    build:
      context: ../shared/echo
    container_name: pp-webserver1
    hostname: service1

  service2:
    build:
      context: ../shared/echo
    container_name: pp-webserver2
    hostname: service2

  go-control-plane:
    build:
      context: .
      dockerfile: Dockerfile-control-plane
    container_name: pp-controlplane-server
    command: bin/example
    healthcheck:
      test: nc -zv localhost 18000
